### ISSUE TITLE
ImportError: cannot import name BACKEND_ALIASES

### ISSUE THREAD

**Issue by dcox** [dealertrack/celery-redis-sentinel#9]
Hi, I would like to use this package but I get the following error:

```
>>> from celery_redis_sentinel import register
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/celery_redis_sentinel/register.py", line 4, in <module>
    from celery.backends import BACKEND_ALIASES
ImportError: cannot import name BACKEND_ALIASES
```

I thought there was an issue with $PYTHONPATH but `from celery import backends` works fine. Do you have any advice? 

I am running Mac OS X, Python 2.7.12. Thanks for taking a look!

**Comment by miki725** [comment]
which celery version?

**Comment by dcox** [comment]
Oops, I forgot to include that. This is happening with 4.0.2.

**Comment by dcox** [comment]
I just downgraded to version 3.1.23 and it seems to be working better, I will stick with Celery 3. Thank you!

**Comment by tsionyx** [comment]
I see this was fixed in 1696912c61879715d29ce5cdb1060b22644326e2. @miki725 could you please upload the the last version on pypi?

**Comment by arthurzenika** [comment]
This could be also fixed with a stricter dependency in the packaging. (as well as the fix noted in the comment above).

**Comment by wjdp** [comment]
Just hit this issue, @miki725 can you create a release?

This repo hasn't been updated in a while. Is there a better way (now 2018) to use redis as a results backend with sentinel?

I note Celery now supports sentinel as a broker, but not as a results backend: http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#results.

**Comment by HungPhann** [comment]
Do we have a plan to create a new release with the latest code?
